name: clockify
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.17
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  stop_watch_timer:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: Nunito Sans
      fonts: 
        - asset: assets/fonts/Nunito-Variable.ttf
          weight: 400
        - asset: assets/fonts/Nunito-VariableItalic.ttf
          weight: 400
          style: italic


